default_stages: [commit]

repos:

- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
    - id: isort
      stages: [ commit ]

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    stages: [commit]

- repo:  https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
      exclude: ^.*/templates/.*$
    - id: check-merge-conflict
    - id: check-toml
      exclude: ^.*/templates/.*$
    - id: mixed-line-ending
      stages: [commit]
    - id: check-yaml